//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TanHoaPushNotification
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tanhoaEntities : DbContext
    {
        public tanhoaEntities()
            : base("name=tanhoaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_Channel_Configurations> t_Channel_Configurations { get; set; }
        public virtual DbSet<t_HistoryPushNotification> t_HistoryPushNotification { get; set; }
        public virtual DbSet<t_Sites> t_Sites { get; set; }
    }
}
