//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TanHoaPushNotification
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Sites
    {
        public string SiteId { get; set; }
        public string SiteAliasName { get; set; }
        public string Location { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string DisplayGroup { get; set; }
        public Nullable<byte> Zoom { get; set; }
        public string ConsumerId { get; set; }
        public string LoggerId { get; set; }
        public Nullable<byte> StartDay { get; set; }
        public string Description { get; set; }
        public string MeterSerial { get; set; }
        public string TransmitterSerial { get; set; }
        public string LoggerSerial { get; set; }
        public Nullable<System.DateTime> MeterDateChanged { get; set; }
        public Nullable<System.DateTime> TransmitterDateChanged { get; set; }
        public Nullable<System.DateTime> LoggerDateChanged { get; set; }
        public string Availability { get; set; }
        public string Status { get; set; }
        public string Staffs { get; set; }
        public Nullable<int> LabelAnchorX { get; set; }
        public Nullable<int> LabelAnchorY { get; set; }
        public Nullable<double> LabelLat { get; set; }
        public Nullable<double> LabelLng { get; set; }
        public string PipeSize { get; set; }
        public Nullable<int> SetDelayTime { get; set; }
        public Nullable<double> SetDiffValue { get; set; }
        public Nullable<double> Baseline { get; set; }
        public string DMA_In { get; set; }
        public string DMA_Out { get; set; }
        public Nullable<bool> DisplayOnGraph { get; set; }
    }
}
