//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class DeviceTokenApp
{
    public int id { get; set; }
    public string Username { get; set; }
    public string DeviceToken { get; set; }
    public Nullable<bool> Status { get; set; }
    public Nullable<bool> Sound { get; set; }
}

public partial class t_Accreditation_Types
{
    public t_Accreditation_Types()
    {
        this.t_Accreditations = new HashSet<t_Accreditations>();
    }

    public string Type { get; set; }
    public string Description { get; set; }

    public virtual ICollection<t_Accreditations> t_Accreditations { get; set; }
}

public partial class t_Accreditations
{
    public string AccreditationDocument { get; set; }
    public string MeterSerial { get; set; }
    public string TransmitterSerial { get; set; }
    public string AccreditationType { get; set; }
    public System.DateTime AccreditationDate { get; set; }
    public Nullable<System.DateTime> ExpiryDate { get; set; }
    public string Description { get; set; }

    public virtual t_Accreditation_Types t_Accreditation_Types { get; set; }
    public virtual t_Meters t_Meters { get; set; }
    public virtual t_Transmitters t_Transmitters { get; set; }
}

public partial class t_Channel_Configurations
{
    public string ChannelId { get; set; }
    public string LoggerId { get; set; }
    public string ChannelName { get; set; }
    public string Unit { get; set; }
    public string Description { get; set; }
    public Nullable<bool> Pressure1 { get; set; }
    public Nullable<bool> Pressure2 { get; set; }
    public Nullable<bool> ForwardFlow { get; set; }
    public Nullable<bool> ReverseFlow { get; set; }
    public Nullable<System.DateTime> TimeStamp { get; set; }
    public Nullable<double> LastValue { get; set; }
    public Nullable<System.DateTime> IndexTimeStamp { get; set; }
    public Nullable<double> LastIndex { get; set; }
    public Nullable<bool> DisplayOnLabel { get; set; }
    public Nullable<bool> ChannelOther { get; set; }
    public Nullable<double> basemin { get; set; }
    public Nullable<double> basemax { get; set; }
    public string GroupChannel { get; set; }
    public Nullable<bool> DisplayOnGraph { get; set; }
    public Nullable<double> Baseline { get; set; }
    public Nullable<bool> StatusViewAlarm { get; set; }
    public Nullable<double> Offset { get; set; }

    public virtual t_Logger_Configurations t_Logger_Configurations { get; set; }
    public virtual t_Units t_Units { get; set; }
}

public partial class t_Consumers
{
    public t_Consumers()
    {
        this.t_Sites = new HashSet<t_Sites>();
        this.t_Users = new HashSet<t_Users>();
    }

    public string ConsumerId { get; set; }
    public Nullable<byte> Zoom { get; set; }
    public string Description { get; set; }

    public virtual ICollection<t_Sites> t_Sites { get; set; }
    public virtual ICollection<t_Users> t_Users { get; set; }
}

public partial class t_Control_Sampler
{
    public int id { get; set; }
    public string stationId { get; set; }
    public string ipaddress { get; set; }
    public string port { get; set; }
    public string partnerId { get; set; }
    public string time { get; set; }
}

public partial class t_Data_Complexes
{
    public string LoggerId { get; set; }
    public System.DateTime TimeStamp { get; set; }
    public Nullable<double> ForwardFlow { get; set; }
    public Nullable<double> ReverseFlow { get; set; }
    public Nullable<double> ForwardIndex { get; set; }
    public Nullable<double> ReverseIndex { get; set; }
    public Nullable<double> Pressure1 { get; set; }
    public Nullable<double> Pressure2 { get; set; }
    public Nullable<double> MinForwardFlow { get; set; }
    public Nullable<double> MaxForwardFlow { get; set; }
    public Nullable<double> MinReverseFlow { get; set; }
    public Nullable<double> MaxReverseFlow { get; set; }
    public Nullable<double> MinPressure1 { get; set; }
    public Nullable<double> MaxPressure1 { get; set; }
    public Nullable<double> MinPressure2 { get; set; }
    public Nullable<double> MaxPressure2 { get; set; }

    public virtual t_Logger_Configurations t_Logger_Configurations { get; set; }
}

public partial class t_Data_Raw_Indexes
{
    public string SiteId { get; set; }
    public System.DateTime TimeStamp { get; set; }
    public double Index { get; set; }
    public string Description { get; set; }
    public Nullable<double> Production { get; set; }

    public virtual t_Sites t_Sites { get; set; }
}

public partial class t_Device_Status
{
    public string Status { get; set; }
    public string Description { get; set; }
    public string Language { get; set; }
}

public partial class t_DisplayGroups
{
    public t_DisplayGroups()
    {
        this.t_Sites = new HashSet<t_Sites>();
    }

    public string Group { get; set; }
    public string Description { get; set; }
    public string Name { get; set; }

    public virtual ICollection<t_Sites> t_Sites { get; set; }
}

public partial class t_Emails
{
    public string Email { get; set; }
    public string Password { get; set; }
    public string Role { get; set; }
}

public partial class t_Function
{
    public int FunctionId { get; set; }
    public string FunctionName { get; set; }
    public string URL { get; set; }
    public Nullable<bool> IsOnMenu { get; set; }
    public Nullable<int> ParentId { get; set; }
    public Nullable<int> Sort { get; set; }
    public string Note { get; set; }
    public string Language { get; set; }
}

public partial class t_GroupChannel
{
    public string GroupChannel { get; set; }
    public string Description { get; set; }
    public Nullable<int> Status { get; set; }
}

public partial class t_Language
{
    public int Id { get; set; }
    public string LangCode { get; set; }
    public string Country { get; set; }
    public string Noted { get; set; }
}

public partial class t_LanguageTranslate
{
    public int Id { get; set; }
    public string ControlId { get; set; }
    public string Contents { get; set; }
    public string Noted { get; set; }
    public string Language { get; set; }
}

public partial class t_Logger_Configurations
{
    public t_Logger_Configurations()
    {
        this.t_Channel_Configurations = new HashSet<t_Channel_Configurations>();
        this.t_Data_Complexes = new HashSet<t_Data_Complexes>();
        this.t_Sites = new HashSet<t_Sites>();
    }

    public string LoggerId { get; set; }
    public string SiteId { get; set; }
    public Nullable<byte> StartHour { get; set; }
    public string TelephoneNumber { get; set; }
    public Nullable<byte> Pressure1 { get; set; }
    public Nullable<byte> Pressure2 { get; set; }
    public Nullable<byte> ForwardFlow { get; set; }
    public Nullable<byte> ReverseFlow { get; set; }
    public Nullable<bool> Alarm { get; set; }
    public Nullable<int> TimeDelayAlarm { get; set; }
    public Nullable<byte> Interval { get; set; }
    public Nullable<bool> Status1 { get; set; }
    public Nullable<bool> Status2 { get; set; }
    public Nullable<int> TimeOffset { get; set; }
    public Nullable<byte> ChannelOther { get; set; }

    public virtual ICollection<t_Channel_Configurations> t_Channel_Configurations { get; set; }
    public virtual ICollection<t_Data_Complexes> t_Data_Complexes { get; set; }
    public virtual ICollection<t_Sites> t_Sites { get; set; }
}

public partial class t_Logger_Files
{
    public int FileID { get; set; }
    public string FileName { get; set; }
    public string LoggerSerial { get; set; }
    public string MIMEType { get; set; }
    public Nullable<int> Size { get; set; }
    public string Path { get; set; }
    public Nullable<System.DateTime> UploadDate { get; set; }

    public virtual t_Loggers t_Loggers { get; set; }
}

public partial class t_Logger_Histories
{
    public int HistoryID { get; set; }
    public string SiteID { get; set; }
    public System.DateTime DateChanged { get; set; }
    public string OldLoggerSerial { get; set; }
    public string NewLoggerSerial { get; set; }
    public Nullable<double> Index { get; set; }
    public string Description { get; set; }

    public virtual t_Loggers t_Loggers { get; set; }
    public virtual t_Sites t_Sites { get; set; }
}

public partial class t_Loggers
{
    public t_Loggers()
    {
        this.t_Logger_Files = new HashSet<t_Logger_Files>();
        this.t_Logger_Histories = new HashSet<t_Logger_Histories>();
        this.t_Sites = new HashSet<t_Sites>();
    }

    public string Serial { get; set; }
    public Nullable<System.DateTime> ReceiptDate { get; set; }
    public string Provider { get; set; }
    public string Marks { get; set; }
    public string Model { get; set; }
    public string Status { get; set; }
    public string Description { get; set; }
    public Nullable<bool> Installed { get; set; }

    public virtual ICollection<t_Logger_Files> t_Logger_Files { get; set; }
    public virtual ICollection<t_Logger_Histories> t_Logger_Histories { get; set; }
    public virtual ICollection<t_Sites> t_Sites { get; set; }
}

public partial class t_Meter_Files
{
    public int FileID { get; set; }
    public string FileName { get; set; }
    public string MeterSerial { get; set; }
    public string MIMEType { get; set; }
    public Nullable<int> Size { get; set; }
    public string Path { get; set; }
    public Nullable<System.DateTime> UploadDate { get; set; }

    public virtual t_Meters t_Meters { get; set; }
}

public partial class t_Meter_Histories
{
    public int HistoryID { get; set; }
    public string SiteID { get; set; }
    public System.DateTime DateChanged { get; set; }
    public string OldMeterSerial { get; set; }
    public string OldAccreditation { get; set; }
    public Nullable<double> OldIndex { get; set; }
    public string NewMeterSerial { get; set; }
    public string NewAccreditation { get; set; }
    public Nullable<double> NewIndex { get; set; }
    public string Description { get; set; }

    public virtual t_Meters t_Meters { get; set; }
}

public partial class t_Meters
{
    public t_Meters()
    {
        this.t_Accreditations = new HashSet<t_Accreditations>();
        this.t_Meter_Files = new HashSet<t_Meter_Files>();
        this.t_Meter_Histories = new HashSet<t_Meter_Histories>();
        this.t_Sites = new HashSet<t_Sites>();
    }

    public string Serial { get; set; }
    public Nullable<System.DateTime> ReceiptDate { get; set; }
    public string Provider { get; set; }
    public string Marks { get; set; }
    public Nullable<short> Size { get; set; }
    public string Model { get; set; }
    public string Status { get; set; }
    public string Description { get; set; }
    public Nullable<bool> Installed { get; set; }
    public string AccreditationDocument { get; set; }
    public string ApprovalDecision { get; set; }
    public Nullable<System.DateTime> ApprovedDate { get; set; }
    public Nullable<bool> Approved { get; set; }

    public virtual ICollection<t_Accreditations> t_Accreditations { get; set; }
    public virtual ICollection<t_Meter_Files> t_Meter_Files { get; set; }
    public virtual ICollection<t_Meter_Histories> t_Meter_Histories { get; set; }
    public virtual ICollection<t_Sites> t_Sites { get; set; }
}

public partial class t_RoleFunction
{
    public string Role { get; set; }
    public int FunctionId { get; set; }
    public Nullable<bool> Active { get; set; }
}

public partial class t_Roles
{
    public t_Roles()
    {
        this.t_Users = new HashSet<t_Users>();
    }

    public string Role { get; set; }
    public string Description { get; set; }

    public virtual ICollection<t_Users> t_Users { get; set; }
}

public partial class t_Site_Availabilities
{
    public t_Site_Availabilities()
    {
        this.t_Sites = new HashSet<t_Sites>();
    }

    public string Availability { get; set; }
    public string Description { get; set; }
    public string Language { get; set; }

    public virtual ICollection<t_Sites> t_Sites { get; set; }
}

public partial class t_Site_Files
{
    public int FileID { get; set; }
    public string FileName { get; set; }
    public string SiteID { get; set; }
    public string MIMEType { get; set; }
    public Nullable<int> Size { get; set; }
    public string Path { get; set; }
    public Nullable<System.DateTime> UploadDate { get; set; }

    public virtual t_Sites t_Sites { get; set; }
}

public partial class t_Site_Status
{
    public t_Site_Status()
    {
        this.t_Sites = new HashSet<t_Sites>();
    }

    public string Status { get; set; }
    public string Description { get; set; }
    public string Language { get; set; }

    public virtual ICollection<t_Sites> t_Sites { get; set; }
}

public partial class t_Sites
{
    public t_Sites()
    {
        this.t_Data_Raw_Indexes = new HashSet<t_Data_Raw_Indexes>();
        this.t_Logger_Histories = new HashSet<t_Logger_Histories>();
        this.t_Site_Files = new HashSet<t_Site_Files>();
    }

    public string SiteId { get; set; }
    public string Location { get; set; }
    public Nullable<double> Latitude { get; set; }
    public Nullable<double> Longitude { get; set; }
    public string DisplayGroup { get; set; }
    public Nullable<byte> Zoom { get; set; }
    public string ConsumerId { get; set; }
    public string LoggerId { get; set; }
    public Nullable<byte> StartDay { get; set; }
    public string Description { get; set; }
    public string MeterSerial { get; set; }
    public string TransmitterSerial { get; set; }
    public string LoggerSerial { get; set; }
    public Nullable<System.DateTime> MeterDateChanged { get; set; }
    public Nullable<System.DateTime> TransmitterDateChanged { get; set; }
    public Nullable<System.DateTime> LoggerDateChanged { get; set; }
    public string Availability { get; set; }
    public string Status { get; set; }
    public string Staffs { get; set; }
    public string SiteAliasName { get; set; }
    public Nullable<int> LabelAnchorX { get; set; }
    public Nullable<int> LabelAnchorY { get; set; }
    public Nullable<double> LabelLat { get; set; }
    public Nullable<double> LabelLng { get; set; }
    public string PipeSize { get; set; }
    public Nullable<int> SetDelayTime { get; set; }
    public Nullable<double> SetDiffValue { get; set; }
    public Nullable<double> Baseline { get; set; }
    public Nullable<bool> DisplayOnGraph { get; set; }
    public string DMA_In { get; set; }
    public string DMA_Out { get; set; }

    public virtual t_Consumers t_Consumers { get; set; }
    public virtual ICollection<t_Data_Raw_Indexes> t_Data_Raw_Indexes { get; set; }
    public virtual t_DisplayGroups t_DisplayGroups { get; set; }
    public virtual t_Logger_Configurations t_Logger_Configurations { get; set; }
    public virtual ICollection<t_Logger_Histories> t_Logger_Histories { get; set; }
    public virtual t_Loggers t_Loggers { get; set; }
    public virtual t_Meters t_Meters { get; set; }
    public virtual t_Site_Availabilities t_Site_Availabilities { get; set; }
    public virtual ICollection<t_Site_Files> t_Site_Files { get; set; }
    public virtual t_Site_Status t_Site_Status { get; set; }
    public virtual t_Transmitters t_Transmitters { get; set; }
}

public partial class t_Staffs
{
    public t_Staffs()
    {
        this.t_Users = new HashSet<t_Users>();
    }

    public string StaffId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Address { get; set; }
    public string TelephoneNumber { get; set; }

    public virtual ICollection<t_Users> t_Users { get; set; }
}

public partial class t_SysParam
{
    public int ID { get; set; }
    public string Name { get; set; }
    public string Val { get; set; }
    public string Val2 { get; set; }
    public string Description { get; set; }
    public Nullable<bool> IsSystem { get; set; }
    public bool Activated { get; set; }
    public string LanguageId { get; set; }
}

public partial class t_TakeSampleHistory
{
    public int ID { get; set; }
    public string SiteID { get; set; }
    public System.DateTime TimeStamp { get; set; }
    public bool Status { get; set; }
    public string UserTake { get; set; }
    public string Type { get; set; }
    public string Description { get; set; }
    public bool IsNotified { get; set; }
}

public partial class t_Transmitter_Files
{
    public int FileID { get; set; }
    public string FileName { get; set; }
    public string TransmitterSerial { get; set; }
    public string MIMEType { get; set; }
    public Nullable<int> Size { get; set; }
    public string Path { get; set; }
    public Nullable<System.DateTime> UploadDate { get; set; }

    public virtual t_Transmitters t_Transmitters { get; set; }
}

public partial class t_Transmitter_Histories
{
    public int HistoryID { get; set; }
    public string SiteID { get; set; }
    public System.DateTime DateChanged { get; set; }
    public string OldTransmitterSerial { get; set; }
    public string OldAccreditation { get; set; }
    public string NewTransmitterSerial { get; set; }
    public string NewAccreditation { get; set; }
    public Nullable<double> Index { get; set; }
    public string Description { get; set; }

    public virtual t_Transmitters t_Transmitters { get; set; }
}

public partial class t_Transmitters
{
    public t_Transmitters()
    {
        this.t_Accreditations = new HashSet<t_Accreditations>();
        this.t_Sites = new HashSet<t_Sites>();
        this.t_Transmitter_Files = new HashSet<t_Transmitter_Files>();
        this.t_Transmitter_Histories = new HashSet<t_Transmitter_Histories>();
    }

    public string Serial { get; set; }
    public Nullable<System.DateTime> ReceiptDate { get; set; }
    public string Provider { get; set; }
    public string Marks { get; set; }
    public Nullable<short> Size { get; set; }
    public string Model { get; set; }
    public string Status { get; set; }
    public string Description { get; set; }
    public Nullable<bool> Installed { get; set; }
    public string AccreditationDocument { get; set; }
    public string ApprovalDecision { get; set; }
    public Nullable<System.DateTime> ApprovedDate { get; set; }
    public Nullable<bool> Approved { get; set; }

    public virtual ICollection<t_Accreditations> t_Accreditations { get; set; }
    public virtual ICollection<t_Sites> t_Sites { get; set; }
    public virtual ICollection<t_Transmitter_Files> t_Transmitter_Files { get; set; }
    public virtual ICollection<t_Transmitter_Histories> t_Transmitter_Histories { get; set; }
}

public partial class t_Units
{
    public t_Units()
    {
        this.t_Channel_Configurations = new HashSet<t_Channel_Configurations>();
    }

    public string Unit { get; set; }
    public string Description { get; set; }

    public virtual ICollection<t_Channel_Configurations> t_Channel_Configurations { get; set; }
}

public partial class t_Users
{
    public string Username { get; set; }
    public string Password { get; set; }
    public string Salt { get; set; }
    public string StaffId { get; set; }
    public string ConsumerId { get; set; }
    public string Email { get; set; }
    public string Role { get; set; }
    public Nullable<bool> Active { get; set; }
    public Nullable<System.DateTime> TimeStamp { get; set; }
    public string Ip { get; set; }
    public Nullable<int> LoginTime { get; set; }
    public string Language { get; set; }

    public virtual t_Consumers t_Consumers { get; set; }
    public virtual t_Roles t_Roles { get; set; }
    public virtual t_Staffs t_Staffs { get; set; }
}

public partial class ComplexData
{
    public Nullable<int> Nr { get; set; }
    public string SiteId { get; set; }
    public string SiteAliasName { get; set; }
    public string LoggerId { get; set; }
    public string Location { get; set; }
    public Nullable<System.DateTime> TimeStamp { get; set; }
    public Nullable<double> Pressure1 { get; set; }
    public Nullable<double> Pressure2 { get; set; }
    public Nullable<double> ForwardFlow { get; set; }
    public Nullable<double> ReverseFlow { get; set; }
    public Nullable<double> ForwardIndex { get; set; }
    public Nullable<double> ReverseIndex { get; set; }
    public string Alarm { get; set; }
    public Nullable<double> NetIndex { get; set; }
    public string Pressure1Unit { get; set; }
    public string Pressure2Unit { get; set; }
    public string ForwardFlowUnit { get; set; }
    public string ReverseFlowUnit { get; set; }
}

public partial class t_Logger_Data
{
    public System.DateTime TimeStamp { get; set; }
    public Nullable<double> Value { get; set; }
}
