using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using Telerik.Web.UI;

public partial class _controls_meter : System.Web.UI.UserControl
{
    protected void Page_Load(object sender, EventArgs e)
    {

    }
    protected void grvM_ItemCommand(object sender, Telerik.Web.UI.GridCommandEventArgs e)
    {
        if (e.CommandName == RadGrid.InitInsertCommandName)
        {
            e.Canceled = true;
            //Prepare an IDictionary with the predefined values  
            System.Collections.Specialized.ListDictionary newValues = new System.Collections.Specialized.ListDictionary();

            //set initial checked state for the checkbox on init insert  
            newValues["Installed"] = false;

            newValues["Approved"] = false;
            //Insert the item and rebind  
            e.Item.OwnerTableView.InsertItem(newValues);

            GridEditCommandColumn editColumn = (GridEditCommandColumn)grvM.MasterTableView.GetColumn("AutoGeneratedEditColumn");
            editColumn.Visible = false;
        }
        else if (e.CommandName == RadGrid.RebindGridCommandName && e.Item.OwnerTableView.IsItemInserted)
        {
            e.Canceled = true;
        }
        else
        {
            GridEditCommandColumn editColumn = (GridEditCommandColumn)grvM.MasterTableView.GetColumn("AutoGeneratedEditColumn");
            if (!editColumn.Visible)
                editColumn.Visible = true;
        }
    }
}